baseURL: https://zhulabtest.netlify.app/
title: zhulq
theme: meghna-hugo

paginate: '6'
summaryLength: '15'

disqusShortname: ''
disableLanguages: []
params:
  # author: Themefisher
  cookies:
    enable: no
    expire_days: 2
  # description: Responsive Multipurpose Parallax Hugo Template
  google_analytics_id: ''
  logo: images/zhulqlogo.jpg
  map:
    enable: no
    gmap_api: https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/slick/slick.css
      - link: https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap
    js:
      - link: plugins/jquery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/lazy-load/lozad.min.js
      - link: plugins/google-map/map.js
  post_share: yes
  preloader:
    enable: no
    preloader: images/logo.png
  # social:
  #   - icon: ti-facebook
  #     link: '#'
  #   - icon: ti-twitter-alt
  #     link: '#'
  #   - icon: ti-youtube
  #     link: '#'
  #   - icon: ti-linkedin
  #     link: '#'
  #   - icon: ti-dribbble
  #     link: '#'
  #   - icon: ti-pinterest
  #     link: '#'
Languages:
  en:
    contentDir: content/english
    # copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com)
      # & Developed by [Gethugothemes](https://gethugothemes.com)
    home: Home
    languageCode: en-us
    languageName: En
    menu:
      main:
        - name: about
          url: '#about'
          weight: 1
        - name: services
          url: '#services'
          weight: 2
        - name: portfolio
          url: '#portfolio'
          weight: 3
        - name: team
          url: '#team'
          weight: 4
        - name: pricing
          url: '#pricing'
          weight: 5
        - name: blog
          url: '#blog'
          weight: 6
        - name: contact
          url: '#contact'
          weight: 7
        - hasChildren: yes
          name: Dropdown
          weight: 7
        - name: Dropdown 1
          parent: Dropdown
          url: '#'
          weight: 1
        - name: Dropdown 2
          parent: Dropdown
          url: '#'
          weight: 2
        # - name: themefisher
        #   url: https://themefisher.com/
        #   weight: 8
    weight: 1
  fr:
    contentDir: content/french
    copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com)
      & Developed by [Gethugothemes](https://gethugothemes.com)
    home: Accueil
    languageCode: fr-fr
    languageName: Fr
    menu:
      main:
        - name: sur
          url: '#about'
          weight: 1
        - name: un service
          url: '#services'
          weight: 2
        - name: portefeuille
          url: '#portfolio'
          weight: 3
        - name: équipe
          url: '#team'
          weight: 4
        - name: tarification
          url: '#pricing'
          weight: 5
        - name: blog
          url: '#blog'
          weight: 6
        - name: contact
          url: '#contact'
          weight: 7
        - name: themefisher
          url: https://themefisher.com/
          weight: 8
    weight: 2
  zh:
    contentDir: content/zh
    # copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com)
      # & Developed by [Gethugothemes](https://gethugothemes.com)
    home: 主页
    languageCode: zh
    languageName: 中文
    menu:
      main:
        - name: 首页
          url: '#about'
          weight: 1
        - name: 新闻
          url: '#services'
          weight: 2
        # - name: portfolio
        #   url: '#portfolio'
        #   weight: 3
        - name: 团队
          url: '#team'
          weight: 4
        # - name: 文章
        #   url: '#pricing'
        #   weight: 5
        - name: 文章
          url: '#blog'
          weight: 6
        - name: 联系我们
          url: '#contact'
          weight: 7
        # - hasChildren: yes
        #   name: Dropdown
        #   weight: 7
        # - name: Dropdown 1
        #   parent: Dropdown
        #   url: '#'
        #   weight: 1
        # - name: Dropdown 2
        #   parent: Dropdown
        #   url: '#'
        #   weight: 2
        # - name: themefisher
        #   url: https://themefisher.com/
        #   weight: 8
    weight: 1
